server:
  port: 9000
spring:
  application:
    name: zuul-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
zuul:
  routes:
    employee:
      service-id: atguigu-feign-consumer
      path: /zuul-emp/**